{
 "title": "[DOCKER] Container Resource Usage",
 "description": "Real-time monitoring of resource consumption (CPU, RAM, Network) per individual Docker container, providing isolation and performance insights.",
 "tags": [
  "cadvisor",
  "docker"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": { "query": "label_values(up,instance)" } },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total,name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$host\",name=~\"$container\",name=~\".+\"}[5m])) by (name) *100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{instance=~\"$host\",name=~\"$container\",name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_cache{instance=~\"$host\",name=~\"$container\",name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$host\",name=~\"$container\",name=~\".+\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"$host\",name=~\"$container\",name=~\".+\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Containers Info",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{instance=~\"$host\",name=~\"$container\",name=~\".+\"})/86400",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=~\".+\", container=~\"$container\"} != \"/metrics\""
    }
   ]
  }
 ]
}