{
 "title": "[LOGS] Infrastructure Live Logs",
 "description": "Aggregated real-time log stream from all containers, enabling rapid debugging and error identification through centralized log management.",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Logs Volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({container=\"lab-postgres\"} | pattern \"<_> <_> <_> [<_>]: [<_>] user=<_>,db=<_>,app=<_>,client=<_> <level>: <_>\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Security & Critical Errors",
   "type": "logs",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"lab-postgres\"} |~ \"(?i)FATAL\""
    }
   ]
  },
  {
   "title": "Live Stream - All Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"lab-postgres\"} |= ``"
    }
   ]
  },
  {
   "title": "Failed Access Attempts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({container=\"lab-postgres\"} |= \"FATAL\" [$__range])"
    }
   ]
  }
 ]
}